### ISSUE TITLE
Transparenta lista

### ISSUE THREAD

**Issue by cotibi** [cotibi/hello-world#2]
Cum fac sa fie lista transparenta (sa se vada navbar-ul de sub ea)? Fara sa-i dau culoarea navbar-ului

**Comment by MercurA** [comment]
Transparency can be achieved in two ways:
 - by opacity: 0
 - by using background-color: rgba(255,255,255,.5) the `a` in rgba stands for alpha. It will make the color transparent so you can see the underlying layout
